/**
 * Created by Administrator on 2017/2/8.
 */
angular.module("RouteModule",["ngRoute"])
    .config(['$routeProvider',function($routeProvider){
        //使用$routeProvider服务处理各种锚点的值,并返回不同的页面
        $routeProvider
            .when("/鲜货直供",{
                templateUrl:'home/html/fresh_fruit.html',
                controller:'homeCtrl'
            })
            .when("/疯狂秒杀",{
                templateUrl:'home/html/crazy.html',
                controller:'homeCtrl'
            })
            .when("/problem",{
                css:'mine/css/problem.css',
                templateUrl:'mine/html/problem.html',
                controller:'mineCtrl'
            })
            .when("/view",{
                css:'mine/css/view.css',
                templateUrl:'mine/html/view.html',
                controller:'mineCtrl'
            })
            .when("/help",{
                css:'mine/css/help.css',
                templateUrl:'mine/html/help.html',
                controller:'mineCtrl'
            })
            .when("/exchange",{
                css:'mine/css/integral_exchange.css',
                templateUrl:'mine/html/integral_exchange.html',
                controller:'mineCtrl'
            })
            .when("/search",{
                templateUrl:'home/html/search.html',
                controller:'homeCtrl'
            })
            .when("/skill",{
                css:'home/css/skill.css',
                templateUrl:'home/html/skill.html',
                controller:'homeCtrl'
            })
            .when("/member",{
                css:'mine/css/member.css',
                templateUrl:'mine/html/member.html',
                controller:'mineCtrl'
            })
            .when("/about",{
                css:'mine/css/about.css',
                templateUrl:'mine/html/about.html',
                controller:'mineCtrl'
            })
            .when("/",{
                css:'home/css/home.css',
                templateUrl:'home/html/home.html',
                controller:'homeCtrl'
            })
            .when("/market",{
                css:'super_market/css/market.css',
                templateUrl:'super_market/html/market.html',
                controller:'marketCtrl'
            })
            .when("/shopCar",{
                css:'shop_car/css/shop.css',
                templateUrl:'shop_car/html/shop.html',
                controller:'shopCtrl'
            })
            .when("/mine",{
                css:'mine/css/mine.css',
                templateUrl:'mine/html/mine.html',
                controller:'mineCtrl'
            })
            .otherwise({
                redirectTo:"/"
            })
    }])